# Generated by Django 2.2.6 on 2021-02-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
